#!/bin/bash

if [[ -z $4  ]]; then
{
  echo Usage: $0 Year Month Day Next_Day
  exit 0
};
fi

YEAR=$1
MONTH=$2
DAY=$3
NEXT_DAY=$4

fetch_file()
{
  if [[ ! -s hourly/$1$2-$1$3.osc.gz ]];
  then {
    wget -O hourly/$1$2-$1$3.osc.gz http://planet.openstreetmap.org/hourly/$1$2-$1$3.osc.gz
  };
  fi
  until [[ -s hourly/$1$2-$1$3.osc.gz ]];
  do {
    sleep 300
    wget -O hourly/$1$2-$1$3.osc.gz http://planet.openstreetmap.org/hourly/$1$2-$1$3.osc.gz
  };
  done
};

HOURS="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23"
LAST_HOUR=00
for HOUR in $HOURS
do {
  fetch_file $YEAR$MONTH$DAY $LAST_HOUR $HOUR
  LAST_HOUR=$HOUR
};
done
fetch_file $YEAR$MONTH $DAY$()23 $NEXT_DAY$()00
