#!/bin/bash

if [[ -z $1  ]]; then
{
  echo Usage: $0 Name_of_bzip2-compressed_file
  exit 0
};
fi
PATH=./:$PATH
read -p "Proceeding will drop the current database osm. Do you really want to continue? " CONFIRM

if [[ $CONFIRM != "YES" ]]; then
{
  echo "Aborted on user request"
  exit 0
};
fi

mysql -u osm -posm -e "create database if not exists osm"
mysql -u osm -posm -e "drop database osm"
mysql -u osm -posm -e "create database osm"


mysql -u osm -posm osm -e "create table key_s (id int unsigned, key_ varchar(21844))"
mysql -u osm -posm osm -e "create table value_s (id int unsigned, value_ varchar(21844))"

echo "Collecting statements  ... "

echo "set session myisam_sort_buffer_size = 1073741824;" >init_database.sql
echo "set session max_heap_table_size = 1073741824;" >>init_database.sql
echo "set session tmp_table_size = 1073741824;" >>init_database.sql

echo "alter table key_s add unique key(id), add index(key_);" >>init_database.sql
echo "alter table value_s add unique key(id), add index(value_);" >>init_database.sql

echo "Creating indices and merged tables ... "
mysql -u osm -posm osm <init_database.sql

bunzip2 <$1 | ./import_osm

./init_derived_data YES
