#!/bin/bash

PATH=./:$PATH
CONFIRM=$1
if [[ $1 != "YES" ]]; then
{
  read -p "Proceeding will drop the current derived data in database osm. Do you really want to continue? " CONFIRM
};
fi

if [[ $CONFIRM != "YES" ]]; then
{
  echo "Aborted on user request"
  exit 0
};
fi


echo "drop table if exists rule_names, rule_bodys, conflicts, node_conflicts, way_conflicts, relation_conflicts, areas, area_segments, area_tags, area_origins, area_ways;" >init_derived_data.sql

echo "create table rule_names (id int, name varchar(21844));" >>init_derived_data.sql
echo "create table rule_bodys (id int, rule int, source varchar(21844));" >>init_derived_data.sql

echo "create table conflicts (id int, rule int, line int, stack tinytext, message varchar(21844));" >>init_derived_data.sql
echo "create table node_conflicts (id int, conflict int);" >>init_derived_data.sql
echo "create table way_conflicts (id int, conflict int);" >>init_derived_data.sql
echo "create table relation_conflicts (id int, conflict int);" >>init_derived_data.sql

echo "create table areas (id int, pivot int, pivot_type tinyint);" >>init_derived_data.sql
echo "create table area_segments (id int, ll_idx int, min_lat int, min_lon int, max_lat int, max_lon int);" >>init_derived_data.sql
echo "create table area_tags (id int, key_ int unsigned, value_ int unsigned);" >>init_derived_data.sql
echo "create table area_origins (id int, rule int, line int, stack tinytext);" >>init_derived_data.sql
echo "create table area_ways (id int, way int);" >>init_derived_data.sql

echo "insert rule_names values (0, '');" >>init_derived_data.sql
echo "alter table rule_names add unique key(id), add key(name);" >>init_derived_data.sql
echo "insert rule_bodys values (0, 0, '');" >>init_derived_data.sql
echo "alter table rule_bodys add key(id), add key(rule);" >>init_derived_data.sql
echo "insert conflicts values (0, 0, 0, '', '');" >>init_derived_data.sql
echo "alter table conflicts add unique key(id), add index(rule, stack(27));" >>init_derived_data.sql
echo "alter table node_conflicts add key(id);" >>init_derived_data.sql
echo "alter table way_conflicts add key(id);" >>init_derived_data.sql
echo "alter table relation_conflicts add key(id);" >>init_derived_data.sql
echo "insert areas values (0, 0, 0);" >>init_derived_data.sql
echo "alter table areas add unique key(id), add index(pivot, pivot_type);" >>init_derived_data.sql
echo "alter table area_segments add key(id), add index(ll_idx);" >>init_derived_data.sql
echo "alter table area_tags add key(id);" >>init_derived_data.sql
echo "alter table area_origins add index(id), add index(rule, stack(27));" >>init_derived_data.sql
echo "alter table area_ways add index(id);" >>init_derived_data.sql


echo "Creating tables for derived data ... "

mysql -u osm -posm osm <init_derived_data.sql
