#!/bin/bash

if [[ -z $2  ]]; then
{
  echo Usage: $0 Name_of_bzip2-compressed_file Replicate_Id
  exit 0
};
fi
PATH=./:$PATH
REPLICATE_ID=$2
CONFIRM=$3
if [[ $3 != "YES" ]]; then
{
  read -p "Proceeding will drop the current databases osm_1 and osm_2 and the raw_db. Do you really want to continue? " CONFIRM
};
fi

if [[ $CONFIRM != "YES" ]]; then
{
  echo "Aborted on user request"
  exit 0
};
fi

# rm /opt/osm_why_api/osm_1/*
# echo "Import planet"
# bunzip2 <$1 | ./bin/import_osm --db=osm_1 >testfiles/planet-nodes.log
# 
# pushd /opt/osm_why_api/
# tar cvf - osm_1/ | gzip >/media/buffalo500/osm$2.tar.gz
# ls -l osm_1/
# popd

echo "Init derived data"
./init_derived_data YES

cd bin/
LOCAL_DIR=../replicate
./fetch_osc $2 &

echo "Updating"
while [[ 0 -eq 0 ]];
do
{
  printf -v TDIGIT3 %03u $(($(($REPLICATE_ID + 480)) % 1000))
  ARG=$(($(($REPLICATE_ID + 480)) / 1000))
  printf -v TDIGIT2 %03u $(($ARG % 1000))
  ARG=$(($ARG / 1000))
  printf -v TDIGIT1 %03u $ARG
  
  while [[ ! -d $LOCAL_DIR/$TDIGIT1 ]];
  do
  {
    sleep 60
  };
  done
  while [[ ! -d $LOCAL_DIR/$TDIGIT1/$TDIGIT2 ]];
  do
  {
    sleep 60
  };
  done
  while [[ ! -s $LOCAL_DIR/$TDIGIT1/$TDIGIT2/$TDIGIT3.osc.gz ]];
  do
  {
    sleep 60
  };
  done
  
  ./apply_gz_osc osm_1 $REPLICATE_ID $(($REPLICATE_ID + 480))
  REPLICATE_ID=$(($REPLICATE_ID + 480))
  
  echo "Have a break @ $REPLICATE_ID"
  sleep 240
  echo "One minute left"
  sleep 60
};
done
