#!/bin/bash

read ARG_1 ARG_2 <$OSM3S_DATADIR/rescue_status

if [[ $ARG_1 == "dirty" ]]; then
{
  cp -p $OSM3S_DATADIR/osm_2/* $OSM3S_DATADIR/osm_1/ >/tmp/osm_autorestart
  ARG_1=$ARG_2
 };
fi
if [[ $ARG_2 == "dirty" ]]; then
{
  cp -p $OSM3S_DATADIR/osm_1/* $OSM3S_DATADIR/osm_2/ >/tmp/osm_autorestart
  ARG_2=$ARG_1
 };
fi

cd $OSM3S_BASEDIR/bin/ >>/tmp/osm_autorestart
./init_dispatcher $ARG_1 $ARG_2 >>/tmp/osm_autorestart
