#!/usr/bin/env bash

# Copyright 2008, 2009, 2010, 2011, 2012 Roland Olbricht
#
# This file is part of PT_Diagrams.
#
# PT_Diagrams is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# PT_Diagrams is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with PT_Diagrams.  If not, see <http://www.gnu.org/licenses/>.


ID=0
BBOX=
DEBUG=
EXEC_DIR="$(dirname "$(realpath "$0")")"
BIN_DIR="$(realpath "$EXEC_DIR/../bin")"
CACHE_DIR="/tmp/osm3s_augmented_diffs_cache/"
NUMBER_RE='-?([0-9]+(\.[0-9]*)?|\.[0-9]+)([eE][+-]?[0-9]+)?'
WS='[[:space:]]*'
BBOX_RE="^${WS}${NUMBER_RE}${WS},${WS}${NUMBER_RE}${WS},${WS}${NUMBER_RE}${WS},${WS}${NUMBER_RE}${WS}\$"
ID_RE='^(0|[1-9][0-9]{0,11})$'

bad_request()
{
  echo "Content-Type: text/plain; charset=utf-8"
  echo "Status: 400 Bad Request"
  echo
  echo "$1"
  exit 0
}

set -f
IFS=$'&'
for KEY_VAL in $QUERY_STRING; do
{
  if [[ $KEY_VAL == *=* ]]; then
    RAW_VAL="${KEY_VAL#*=}"
  else
    RAW_VAL=
  fi
  KEY=$(printf '%s' "${KEY_VAL%%=*}" | "$BIN_DIR"/uncgi) || bad_request "Malformed query string"
  VAL=$(printf '%s' "$RAW_VAL" | "$BIN_DIR"/uncgi) || bad_request "Malformed query string"
  case "$KEY" in
    id)
      if [[ $VAL =~ $ID_RE ]]; then
        ID="$VAL"
      else
        bad_request "Invalid id parameter"
      fi
      ;;
    bbox)
      if [[ $VAL =~ $BBOX_RE ]]; then
        if [[ ${VAL:0:4} != "-180" ]]; then
          BBOX="$VAL"
        fi
      else
        bad_request "Invalid bbox parameter"
      fi
      ;;
    debug)
      DEBUG="$VAL"
      ;;
  esac
}; done
unset IFS
set +f

EPOCHSECS=$((ID * 60 + 1347432900))
SINCE=$(date --utc --date="@$EPOCHSECS" '+%FT%H:%M:%SZ')
UNTIL=$(date --utc --date="@$((EPOCHSECS + 60))" '+%FT%H:%M:%SZ')

if [[ -z $BBOX ]]; then

  if [[ -r "$CACHE_DIR/$ID.osc.gz" ]]; then
    # Do HTTP headers with respect to CORS
    echo "Access-Control-Allow-Origin: *"
    echo "Content-Type: application/osm3s+xml"
    echo
    gunzip <"$CACHE_DIR/$ID.osc.gz"
    exit 0
  fi

  QUERY_STRING='data=[adiff:"'$SINCE'","'$UNTIL'"];(node(changed:"'$SINCE'","'$UNTIL'");way(changed:"'$SINCE'","'$UNTIL'");rel(changed:"'$SINCE'","'$UNTIL'"););out meta geom;'
else
  QUERY_STRING='data=[adiff:"'$SINCE'","'$UNTIL'"];(node(bbox)(changed:"'$SINCE'","'$UNTIL'");way(bbox)(changed:"'$SINCE'","'$UNTIL'");rel(bbox)(changed:"'$SINCE'","'$UNTIL'"););out meta geom;&bbox='$BBOX
fi
#REQUEST_METHOD=GET

if [[ -z $DEBUG ]]; then
  "$EXEC_DIR"/interpreter
else
  echo "Content-Type: text/plain"
  echo
  echo "$QUERY_STRING"
fi
