#!/usr/bin/env bash

# Copyright 2008, 2009, 2010, 2011, 2012 Roland Olbricht
#
# This file is part of PT_Diagrams.
#
# PT_Diagrams is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# PT_Diagrams is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with PT_Diagrams.  If not, see <http://www.gnu.org/licenses/>.


CACHE_DIR="/tmp/osm3s_augmented_diffs_cache/"
EXEC_DIR="$(dirname "$(realpath "$0")")"
TIMESTAMP_RE='^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$'
WS='[[:space:]]*'
TOKEN='[!#$%&'"'"'*+.^_`|~[:alnum:]-]+'
HEADERS_RE="^${WS}${TOKEN}(${WS},${WS}${TOKEN})*${WS}\$"

print_cors_headers()
{
  if [[ -n $HTTP_ACCESS_CONTROL_REQUEST_HEADERS && $HTTP_ACCESS_CONTROL_REQUEST_HEADERS =~ $HEADERS_RE ]]; then
    echo "Access-Control-Allow-Headers: $HTTP_ACCESS_CONTROL_REQUEST_HEADERS"
  fi
  if [[ -n $HTTP_ORIGIN ]]; then
    echo "Access-Control-Allow-Origin: *"
  fi
}

internal_error()
{
  echo "Content-Type: text/plain; charset=utf-8"
  echo "Status: 500 Internal Server Error"
  print_cors_headers
  echo
  echo "$1"
  exit 0
}

if [[ $REQUEST_METHOD == "OPTIONS" ]]; then
  echo "Content-Type: text/plain; charset=utf-8"
  print_cors_headers
  echo "Access-Control-Allow-Methods: GET, POST, OPTIONS"
  echo "Content-Length: 0"
  echo
  exit 0
fi

if [[ -r "$CACHE_DIR/newest" ]]; then
  echo "Content-Type: text/plain; charset=utf-8"
  print_cors_headers
  echo
  cat "$CACHE_DIR/newest"
  exit 0
fi

TIMESTAMP=$("$EXEC_DIR"/timestamp | tail -n 1)

if [[ ! $TIMESTAMP =~ $TIMESTAMP_RE ]]; then
  internal_error "Invalid timestamp from backend"
fi

EPOCHSECS=$(date --date="$TIMESTAMP" '+%s')

echo "Content-Type: text/plain; charset=utf-8"
print_cors_headers
echo
echo $(( ( EPOCHSECS - 1347432960 ) / 60 ))
