#!/usr/bin/env bash

# Copyright 2008, 2009, 2010, 2011, 2012 Roland Olbricht
#
# This file is part of PT_Diagrams.
#
# PT_Diagrams is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# PT_Diagrams is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with PT_Diagrams.  If not, see <http://www.gnu.org/licenses/>.

EXEC_DIR="$(dirname "$(realpath "$0")")"
BIN_DIR="$(realpath "$EXEC_DIR/../bin")"

ID=
LAT=50.7421
LON=7.0624
ZOOM=6

NUMBER_RE='-?([0-9]+(\.[0-9]*)?|\.[0-9]+)([eE][+-]?[0-9]+)?'
ID_RE='^(0|[1-9][0-9]{0,11})$'
LAT_RE="^${NUMBER_RE}\$"
LON_RE="^${NUMBER_RE}\$"
ZOOM_RE='^[0-9]{1,2}$'

set -f
IFS=$'&'
for KEY_VAL in $QUERY_STRING; do
{
  if [[ $KEY_VAL == *=* ]]; then
    RAW_VAL="${KEY_VAL#*=}"
  else
    RAW_VAL=
  fi
  KEY=$(printf '%s' "${KEY_VAL%%=*}" | "$BIN_DIR"/uncgi) || continue
  VAL=$(printf '%s' "$RAW_VAL" | "$BIN_DIR"/uncgi) || continue
  case "$KEY" in
    id)
      [[ $VAL =~ $ID_RE ]] && ID="$VAL"
      ;;
    lat)
      [[ $VAL =~ $LAT_RE ]] && LAT="$VAL"
      ;;
    lon)
      [[ $VAL =~ $LON_RE ]] && LON="$VAL"
      ;;
    zoom)
      [[ $VAL =~ $ZOOM_RE ]] && ZOOM="$VAL"
      ;;
  esac
}; done
unset IFS
set +f

echo "Content-Type: text/html; charset=utf-8"
echo

awk -v id="$ID" -v lat="$LAT" -v lon="$LON" -v zoom="$ZOOM" '
{
  line = $0
  sub(/\$ID/, id, line)
  sub(/\$LAT/, lat, line)
  sub(/\$LON/, lon, line)
  sub(/\$ZOOM/, zoom, line)
  print line
}' /var/www/augmented_diffs.html
