#!/usr/bin/env bash

# Copyright 2008, 2009, 2010, 2011, 2012 Roland Olbricht
#
# This file is part of PT_Diagrams.
#
# PT_Diagrams is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# PT_Diagrams is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with PT_Diagrams.  If not, see <http://www.gnu.org/licenses/>.

EXEC_DIR="$(dirname "$(realpath "$0")")"
BIN_DIR="$(realpath "$EXEC_DIR/../bin")"

NUMBER_RE='-?([0-9]+(\.[0-9]*)?|\.[0-9]+)([eE][+-]?[0-9]+)?'
NUMERIC_RE="^${NUMBER_RE}\$"

NETWORK_=
REF_=
SKETCH_PARAMS=
DEBUG=
BASEDIR=

fail()
{
  echo "Content-Type: text/plain; charset=utf-8"
  echo
  echo "$1"
  [[ -n $BASEDIR ]] && rm -rf "$BASEDIR"
  exit 0
}

set -f
IFS=$'&'
for KEY_VAL in $QUERY_STRING; do
{
  if [[ $KEY_VAL == *=* ]]; then
    RAW_VAL="${KEY_VAL#*=}"
  else
    RAW_VAL=
  fi
  KEY=$(printf '%s' "${KEY_VAL%%=*}" | "$BIN_DIR"/uncgi) || fail "Malformed query string"
  VAL=$(printf '%s' "$RAW_VAL" | "$BIN_DIR"/uncgi) || fail "Malformed query string"
  case "$KEY" in
    network)
      NETWORK_=$(printf '%s' "$VAL" | "$BIN_DIR"/escape_xml)
      ;;
    ref)
      REF_=$(printf '%s' "$VAL" | "$BIN_DIR"/escape_xml)
      ;;
    pivot-lon)
      if [[ $VAL =~ $NUMERIC_RE ]]; then
        SKETCH_PARAMS="$SKETCH_PARAMS --pivot-lon=$VAL"
      else
        fail "Invalid pivot-lon parameter."
      fi
      ;;
    scale)
      if [[ $VAL =~ $NUMERIC_RE ]]; then
        SKETCH_PARAMS="$SKETCH_PARAMS --scale=$VAL"
      else
        fail "Invalid scale parameter."
      fi
      ;;
    font-size)
      if [[ $VAL =~ $NUMERIC_RE ]]; then
        SKETCH_PARAMS="$SKETCH_PARAMS --stop-font-size=$VAL"
      else
        fail "Invalid font-size parameter."
      fi
      ;;
    debug)
      DEBUG="$VAL"
      ;;
  esac
}; done
unset IFS
set +f

if [[ -z $REF_ ]]; then
  fail "An empty value for ref is not allowed."
fi

BASEDIR=$(mktemp -d /tmp/osm3s_draw_line_XXXXXX) || fail "Could not create temporary directory."

cat >"$BASEDIR/request.1" <<EOF
<osm-script>
<union>
  <query type="relation">
    <has-kv k="network" v="$NETWORK_"/>
    <has-kv k="ref" v="$REF_"/>
  </query>
  <recurse type="relation-node" into="__"/>
  <recurse type="relation-way"/>
  <recurse type="way-node"/>
</union>
<print mode="body"/>
</osm-script>
EOF

CORRESPONDENCES= #$("$BIN_DIR"/bbox_brim_query --only-corrs $BRIM_PARAMS)

if [[ $CORRESPONDENCES -gt 0 ]]; then
  fail "Correspondences are for the geographical map currently not supported."
fi

export REQUEST_METHOD=
if [[ $DEBUG == "full-query" ]]; then
  echo "Content-Type: text/plain; charset=utf-8"
  echo

  "$BIN_DIR"/osm3s_query <"$BASEDIR/request.1" 2>&1

  echo
  echo "$BIN_DIR/draw_route_svg $SKETCH_PARAMS"
else
  "$BIN_DIR"/osm3s_query --quiet <"$BASEDIR/request.1" >"$BASEDIR/answer.1"
fi

echo "Content-Type: image/svg+xml; charset=utf-8"
echo

# shellcheck disable=SC2086 # SKETCH_PARAMS holds space-separated, regex-validated numeric flags
"$BIN_DIR"/draw_route_svg $SKETCH_PARAMS <"$BASEDIR/answer.1"

rm -rf "$BASEDIR"
