#!/usr/bin/env bash

# Copyright 2008, 2009, 2010, 2011, 2012 Roland Olbricht
#
# This file is part of Overpass_API.
#
# Overpass_API is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Overpass_API is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Overpass_API.  If not, see <http://www.gnu.org/licenses/>.

EXEC_DIR="`dirname $0`/"
if [[ ! ${EXEC_DIR:0:1} == "/" ]]; then
{
  EXEC_DIR="`pwd`/$EXEC_DIR"
};
fi

BIN_DIR="$EXEC_DIR/../bin"

echo "Content-Type: text/plain; charset=utf-8"
echo 'Access-Control-Allow-Origin: *'
echo

COUNTER=16
PID=`$BIN_DIR/dispatcher --query_token`

if [[ $PID == 0 ]]; then
  echo "No query running from IP $REMOTE_ADDR"
fi

while [[ $PID -ne 0 && $COUNTER -gt 0 ]]; do
{
  echo "Killing query (pid $PID) from IP $REMOTE_ADDR ..."
  kill -9 $PID
  echo "Done!"
  
  COUNTER=$(($COUNTER - 1))
  PID=`$BIN_DIR/dispatcher --query_token`
};
done
