#!/usr/bin/env bash

# Copyright 2008, 2009, 2010, 2011, 2012 Roland Olbricht
#
# This file is part of Overpass_API.
#
# Overpass_API is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Overpass_API is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Overpass_API.  If not, see <http://www.gnu.org/licenses/>.

EXEC_DIR="$(dirname "$(realpath "$0")")"
BIN_DIR="$(realpath "$EXEC_DIR/../bin")"

PID_RE='^[0-9]+$'

echo "Content-Type: text/plain; charset=utf-8"
echo 'Access-Control-Allow-Origin: *'
echo

COUNTER=16
PID=$("$BIN_DIR"/dispatcher --query_token)

if [[ -z $PID ]]; then
  echo "No query running from IP $REMOTE_ADDR"
fi

while [[ $PID =~ $PID_RE && $COUNTER -gt 0 ]]; do
  echo "Killing query (pid $PID) from IP $REMOTE_ADDR ..."
  kill -9 "$PID"
  echo "Done!"

  COUNTER=$((COUNTER - 1))
  PID=$("$BIN_DIR"/dispatcher --query_token)
done

if [[ -n $PID && ! $PID =~ $PID_RE ]]; then
  echo "Could not query dispatcher: $PID"
fi
