#!/usr/bin/env bash

# Copyright 2008, 2009, 2010, 2011, 2012 Roland Olbricht
#
# This file is part of Overpass_API.
#
# Overpass_API is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Overpass_API is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Overpass_API.  If not, see <http://www.gnu.org/licenses/>.

# $1 - remote source
# $2 - local destination
fetch_file()
{
  wget -q -O "$2" "$1"
}

fetch_and_output_result()
{
  if fetch_file "$1" "$PING_FILE"; then
    "$BIN_DIR"/escape_xml <"$PING_FILE"
  else
    echo "Fetch failed."
  fi
}

EXEC_DIR="$(dirname "$(realpath "$0")")"
BIN_DIR="$(realpath "$EXEC_DIR/../bin")"

# Set BASE_URL to your own server's external name
BASE_URL="http://localhost/api"

PING_FILE=$(mktemp /tmp/osm3s_ping_XXXXXX) || exit 1
trap 'rm -f "$PING_FILE"' EXIT

echo "Content-Type: text/html; charset=utf-8"
echo
cat <<EOF
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" lang="en"></meta>
  <title>Server status</title>
</head>
<body>
  <h1>Outside view on the server</h1>
  <h2>Empty, simple request</h2>
<pre>

EOF

fetch_and_output_result "$BASE_URL/interpreter?data=<print/>"

cat <<EOF
</pre>  <h2>Meta request</h2>
<pre>

EOF

fetch_and_output_result "$BASE_URL/interpreter?data=<query type='way'><has-kv k='name' v='Lipkenskothen'/></query><print mode='meta'/><recurse type='way-node'/><print mode='meta'/>"

cat <<EOF
</pre>  <h2>Area request</h2>
<pre>

EOF

fetch_and_output_result "$BASE_URL/interpreter?data=<coord-query lat='51.25' lon='7.15'/><print mode='ids_only'/>"

cat <<EOF
</pre></body>
</html>

EOF
