#!/usr/bin/env bash

# Copyright 2008, 2009, 2010, 2011, 2012 Roland Olbricht
#
# This file is part of Overpass_API.
#
# Overpass_API is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Overpass_API is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Overpass_API.  If not, see <http://www.gnu.org/licenses/>.

# $1 - remote source
# $2 - local destination

EXEC_DIR="`dirname $0`/"
if [[ ! ${EXEC_DIR:0:1} == "/" ]]; then
{
  EXEC_DIR="`pwd`/$EXEC_DIR"
};
fi

BIN_DIR="$EXEC_DIR/../bin"

echo "Content-Type: text/html; charset=utf-8"
echo

echo -e "\
<html>\n\
<head>\n\
  <meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" lang=\"en\"></meta>\n\
  <title>Server status</title>\n\
</head>\n\
<body>\n\
  <h1>Outside view on the server</h1>\n\
  <h2>Empty, simple request</h2>\n\
<pre>\n"

echo "<print/>" | $EXEC_DIR/interpreter | $BIN_DIR/escape_xml

echo -e "</pre>\
  <h2>Meta request</h2>\n\
<pre>\n"

echo "<query type='way'><has-kv k='name' v='Lipkenskothen'/></query><print mode='meta'/><recurse type='way-node'/><print mode='meta'/>" | $EXEC_DIR/interpreter | $BIN_DIR/escape_xml

echo -e "</pre>\
  <h2>Area request</h2>\n\
<pre>\n"

echo "<coord-query lat='51.25' lon='7.15'/><print mode='ids_only'/>" | $EXEC_DIR/interpreter | $BIN_DIR/escape_xml

echo -e "</pre>\
</body>\n\
</html>\n"
