#!/usr/bin/env bash

# Copyright 2008, 2009, 2010, 2011, 2012 Roland Olbricht
#
# This file is part of PT_Diagrams.
#
# PT_Diagrams is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# PT_Diagrams is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with PT_Diagrams.  If not, see <http://www.gnu.org/licenses/>.

ARG_RE='^[0-9]+$'

EXEC_DIR="$(dirname "$(realpath "$0")")"
BIN_DIR="$(realpath "$EXEC_DIR/../bin")"

BASEDIR=

fail()
{
  echo "Content-Type: text/plain; charset=utf-8"
  echo
  echo "$1"
  [[ -n $BASEDIR ]] && rm -rf "$BASEDIR"
  exit 0
}

ARG_1_RAW=$(printf '%s\n' "$QUERY_STRING" | awk -F '[=,&]' '{ print $1; }')
ARG_2_RAW=$(printf '%s\n' "$QUERY_STRING" | awk -F '[=,&]' '{ print $2; }')
ARG_3_RAW=$(printf '%s\n' "$QUERY_STRING" | awk -F '[=,&]' '{ print $3; }')

ARG_1=$(printf '%s' "$ARG_1_RAW" | "$BIN_DIR"/uncgi) || fail "Malformed query string"
ARG_2=$(printf '%s' "$ARG_2_RAW" | "$BIN_DIR"/uncgi) || fail "Malformed query string"
ARG_3=$(printf '%s' "$ARG_3_RAW" | "$BIN_DIR"/uncgi) || fail "Malformed query string"

if [[ -n $ARG_1 && ! $ARG_1 =~ $ARG_RE ]]; then
  fail "Invalid relation id"
fi

BASEDIR=$(mktemp -d /tmp/osm3s_sketch_route_XXXXXX) || fail "Could not create temporary directory"

if [[ ( $ARG_2 == "backspace" ) || ($ARG_2 == "backtime") || ($ARG_2 == "debug") ]]; then
  cat >"$BASEDIR/req" <<EOF
<osm-script>
<union>
  <id-query type="relation" ref="$ARG_1"/>
  <recurse type="relation-node"/>
</union>
<print mode="body"/>
</osm-script>
EOF
elif [[ -n $ARG_2 ]]; then
  if [[ ! $ARG_2 =~ $ARG_RE ]]; then
    fail "Invalid relation id"
  fi
  cat >"$BASEDIR/req" <<EOF
<osm-script>
<union>
  <union>
    <id-query type="relation" ref="$ARG_1"/>
    <id-query type="relation" ref="$ARG_2"/>
  </union>
  <recurse type="relation-node"/>
</union>
<print mode="body"/>
</osm-script>
EOF
else
  cat >"$BASEDIR/req" <<EOF
<osm-script>
<union>
  <id-query type="relation" ref="$ARG_1"/>
  <recurse type="relation-node"/>
</union>
<print mode="body"/>
</osm-script>
EOF
fi

export REQUEST_METHOD=
"$BIN_DIR"/osm3s_query --quiet --no-mime <"$BASEDIR/req" >"$BASEDIR/result"

if [[ $ARG_2 == "backspace" ]]; then
  echo "Content-Type: image/svg+xml; charset=utf-8"
  echo

  "$BIN_DIR"/sketch_route_svg --backspace <"$BASEDIR/result"
elif [[ $ARG_2 == "backtime" ]]; then
  echo "Content-Type: image/svg+xml; charset=utf-8"
  echo

  "$BIN_DIR"/sketch_route_svg --backtime <"$BASEDIR/result"
elif [[ ($ARG_2 == "debug") || ($ARG_3 == "debug") ]]; then
  echo "Content-Type: text/plain"
  echo
  cat "$BASEDIR/result"
else
  echo "Content-Type: image/svg+xml; charset=utf-8"
  echo

  "$BIN_DIR"/sketch_route_svg <"$BASEDIR/result"
fi

rm -rf "$BASEDIR"
