#!/usr/bin/env bash

BUF="$QUERY_STRING&"

SKETCH_PARAMS=
BRIM_PARAMS=

EXEC_DIR="`dirname $0`/"
if [[ ! ${EXEC_DIR:0:1} == "/" ]]; then
{
  EXEC_DIR="`pwd`/$EXEC_DIR"
};
fi

BIN_DIR="$EXEC_DIR/../bin"

IFS=$'&'
for KEY_VAL in $QUERY_STRING; do
{
  if [[ ${KEY_VAL:0:8} == "network=" ]]; then
  {
    NETWORK="${KEY_VAL:8}"
    NETWORK_=`echo "${KEY_VAL:8}" | $BIN_DIR/uncgi`
  };
  elif [[ ${KEY_VAL:0:4} == "ref=" ]]; then
  {
    REF="${KEY_VAL:4}"
    REF_=`echo "${KEY_VAL:4}" | $BIN_DIR/uncgi`
  };
  elif [[ ${KEY_VAL:0:6} == "width=" ]]; then
    SKETCH_PARAMS="$SKETCH_PARAMS --width=${KEY_VAL:6}"
  elif [[ ${KEY_VAL:0:7} == "height=" ]]; then
    SKETCH_PARAMS="$SKETCH_PARAMS --height=${KEY_VAL:7}"
  elif [[ ${KEY_VAL:0:10} == "font-size=" ]]; then
    SKETCH_PARAMS="$SKETCH_PARAMS --stop-font-size=${KEY_VAL:10}"
  elif [[ ${KEY_VAL:0:11} == "force-rows=" ]]; then
    SKETCH_PARAMS="$SKETCH_PARAMS --rows=${KEY_VAL:11}"
  elif [[ ${KEY_VAL:0:6} == "style=" ]]; then
  {
    SKETCH_PARAMS="$SKETCH_PARAMS --options=/opt/osm_why_api/options/sketch-line.${KEY_VAL:6}"
    BRIM_PARAMS="$BRIM_PARAMS --options=/opt/osm_why_api/options/sketch-line.${KEY_VAL:6}"
  };
  elif [[ ${KEY_VAL:0:16} == "correspondences=" ]]; then
  {
    SKETCH_PARAMS="$SKETCH_PARAMS --walk-limit=${KEY_VAL:16}"
    BRIM_PARAMS="$BRIM_PARAMS --size=${KEY_VAL:16}"
  };
  elif [[ ${KEY_VAL:0:18} == "max-cors-per-line=" ]]; then
    SKETCH_PARAMS="$SKETCH_PARAMS --max-correspondences-per-line=${KEY_VAL:18}"
  elif [[ ${KEY_VAL:0:15} == "max-cors-below=" ]]; then
    SKETCH_PARAMS="$SKETCH_PARAMS --max-correspondences-below=${KEY_VAL:15}"
  elif [[ ${KEY_VAL:0:6} == "debug=" ]]; then
  {
    SKETCH_PARAMS="$SKETCH_PARAMS --debug=${KEY_VAL:6}"
    DEBUG="${KEY_VAL:6}"
  };
  fi
}; done
unset IFS

BASEDIR=`mktemp -d /tmp/osm3s_sketch_line_XXXXXX`

if [[ -z $REF ]]; then
{                     
  echo "Content-Type: text/plain; charset=utf-8"
  echo                                          
  echo "An empty value for ref is not allowed"  

  exit 0
};    
fi      

if [[ $DEBUG == "yes" ]]; then
{
  echo "Content-Type: text/plain; charset=utf-8"
  echo
  echo $BIN_DIR/bbox_brim_query --network="$NETWORK_" --ref="$REF_" $BRIM_PARAMS ">"$BASEDIR/request.1
  echo
};
fi

$BIN_DIR/bbox_brim_query --network="$NETWORK_" --ref="$REF_" $BRIM_PARAMS >$BASEDIR/request.1

REQUEST_METHOD=

if [[ $DEBUG == "yes" ]]; then
{
  cat <$BASEDIR/request.1
  echo
  echo $BIN_DIR/osm3s_query --verbose "<"$BASEDIR/request.1 ">"$BASEDIR/answer.1
  echo
  $BIN_DIR/osm3s_query --verbose <$BASEDIR/request.1 >$BASEDIR/answer.1 2>$BASEDIR/log.1
  echo
  cat <$BASEDIR/log.1
  cat <$BASEDIR/answer.1
  echo $BIN_DIR/sketch_route_svg --network="$NETWORK_" --ref="$REF_" $SKETCH_PARAMS <$BASEDIR/answer.1
  echo
};
else
  $BIN_DIR/osm3s_query --quiet <$BASEDIR/request.1 >$BASEDIR/answer.1
fi;

echo "Content-Type: image/svg+xml; charset=utf-8"
echo

$BIN_DIR/sketch_route_svg --network="$NETWORK_" --ref="$REF_" $SKETCH_PARAMS <$BASEDIR/answer.1
