#!/usr/bin/env bash

# Copyright 2008, 2009, 2010, 2011, 2012 Roland Olbricht
#
# This file is part of Overpass_API.
#
# Overpass_API is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Overpass_API is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Overpass_API.  If not, see <http://www.gnu.org/licenses/>.

EXEC_DIR="$(dirname "$(realpath "$0")")"
BIN_DIR="$(realpath "$EXEC_DIR/../bin")"

DEBUG=

bad_request()
{
  echo "Content-Type: text/plain; charset=utf-8"
  echo "Status: 400 Bad Request"
  echo
  echo "Error in [$BUF]:"
  echo "$1"
  exit 0
}

BUF=$(printf '%s' "$QUERY_STRING" | "$BIN_DIR"/uncgi) || bad_request "Malformed query string"
if [[ "${BUF:0:5}" == "debug" ]]; then
  DEBUG=yes
  echo "Content-Type: text/plain; charset=utf-8"
  echo
  BUF="${BUF:6}"
  echo "[$BUF]"
fi

# No mkdir - directory should be created and made world-writeable
# by the maintainer to allow periodic cleanups.
XML_REQUEST=$("$BIN_DIR"/translate_xapi --force-meta "$BUF")
EXITCODE=$?
if [[ $EXITCODE -ne 0 ]]; then
  bad_request "$XML_REQUEST"
fi

if [[ $DEBUG == "yes" ]]; then
  printf '%s\n' "$XML_REQUEST"
  echo
fi
export REQUEST_METHOD=
printf '%s' "$XML_REQUEST" | "$EXEC_DIR"/interpreter
