#!/bin/bash

BIN_DIR=../bin
BUF="`echo "$QUERY_STRING" | $BIN_DIR/uncgi`"
if [[ "${BUF:0:5}" == "debug" ]]; then
{
  DEBUG=yes
  echo "Content-Type: text/plain; charset=utf-8"
  echo
  BUF="${BUF:6}"
  echo "[$BUF]"
};
fi
BASEDIR=`mktemp -d`
$BIN_DIR/translate_xapi "${BUF}" >$BASEDIR/request
EXITCODE=$?
if [[ $EXITCODE -ne 0 ]]; then
{
  echo "Content-Type: text/plain; charset=utf-8"
  echo
  echo "Error in [$BUF]:"
  cat <$BASEDIR/request
};
else
{
  if [[ $DEBUG == "yes" ]]; then
  {
    cat <$BASEDIR/request
    echo
  };
  fi
  REQUEST_METHOD=
  ./interpreter <$BASEDIR/request
};
fi
